version: "2"

checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 20
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 50
  method-lines:
    enabled: false
  nested-control-flow:
    config:
      threshold: 5
  return-statements:
    config:
      threshold: 10
  similar-code:
    enabled: false
